<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CXOAI.SkillTester</RootNamespace>
    <AssemblyName>SkillTester</AssemblyName>
    <UserSecretsId>a2b5a2b5-3d99-410a-bc67-6c425da5d05c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.8.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Services\ConfigurationStoreService\ConfigurationStoreService.csproj" />
    <ProjectReference Include="..\..\..\Common\Services\SkillFramework\SkillFramework.csproj" />
    <ProjectReference Include="..\..\..\Tools\CXOAI\CXOAIToolsService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\Common\Services\ConfigurationStoreService\StoreConfigs\test.SeedData.json" Link="StoreConfigs\test.SeedData.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\..\Common\Services\ConfigurationStoreService\StoreConfigs\Skills.json" Link="StoreConfigs\Skills.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="docs\" />
  </ItemGroup>

</Project>
