param POwnerObjectId string
param Pev2CertSubjectName  string
param Pev2keyVaultResourceGroupLocation  string
param PappSubscriptionKey  string
param Pev2keyVaultResourceGroupName string
param Pev2PipelinekeyVaultName string
param Pev2CertkeyVaultPrivateIssuerName  string
param Pev2CertkeyVaultPrivateProviderName  string
param Pev2PipelineCertkeyVaultName  string
param PdeployEv2AssistedIdentityResources string
param Pev2AssistedIdentityAppName string


var ev2certDetail= 'Pev2AssistedIdentityAppName:${Pev2AssistedIdentityAppName}, PdeployEv2AssistedIdentityResources:${PdeployEv2AssistedIdentityResources}, POwnerObjectId:${POwnerObjectId}, Pev2CertSubjectName:${Pev2CertSubjectName}, Pev2keyVaultResourceGroupLocation:${Pev2keyVaultResourceGroupLocation}, PappSubscriptionKey:${PappSubscriptionKey}, Pev2keyVaultResourceGroupName:${Pev2keyVaultResourceGroupName}, Pev2PipelinekeyVaultName:${Pev2PipelinekeyVaultName}, Pev2CertkeyVaultPrivateIssuerName:${Pev2CertkeyVaultPrivateIssuerName}, Pev2CertkeyVaultPrivateProviderName:${Pev2CertkeyVaultPrivateProviderName}, Pev2PipelineCertkeyVaultName:${Pev2PipelineCertkeyVaultName}'
output ev2certDetail string = ev2certDetail
