<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CXOAI.MemoryTester</RootNamespace>
    <AssemblyName>MemoryTester</AssemblyName>
    <UserSecretsId>a2b5a2b5-3d99-410a-bc67-6c425da5d05c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Services\AppServices\CXOAI.AppServices\AppServices.csproj" />
    <ProjectReference Include="..\..\..\Common\Services\MemoryService\MemoryService.csproj" />
    <ProjectReference Include="..\..\..\Common\Services\SkillFramework\SkillFramework.csproj" />
    <ProjectReference Include="..\..\..\Common\Providers\Provider\Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\Functions\CXOAI\EnvironmentSettings\*.json" Link="EnvironmentSettings\%(Filename)%(Extension)">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EnvironmentSettings\" />
  </ItemGroup>

</Project>
