namespace CXOAI.SkillFramework;

/// <summary>
/// One task in the task plan produced by the Task Planner Agent.
/// </summary>
public class TaskPlanItem
{
    /// <summary>Short label describing the task (e.g., "Get CSAT score for Walmart").</summary>
    public string Task { get; set; } = string.Empty;

    /// <summary>Name of the skill/agent to execute (must match a registered skill).</summary>
    public string SkillName { get; set; } = string.Empty;

    /// <summary>Zero-based indices of tasks that must complete before this task can run.
    /// Empty for root tasks (e.g., data-fetching skills with no upstream dependencies).</summary>
    public List<int> DependsOn { get; set; } = [];

    /// <summary>The sub-prompt this skill will receive. Generated by the prompt generation step,
    /// not by the planner.</summary>
    public string PromptToSend { get; set; } = string.Empty;

    /// <summary>Group number for multi-query prompts. Derived automatically from the DAG structure
    /// (connected components). Tasks in independent sub-DAGs get different group numbers.
    /// Not assigned by the LLM — computed by <see cref="PlanGrouper.AssignGroups"/>.</summary>
    public int Group { get; set; }
}

/// <summary>
/// Intermediate model output by the Planner LLM (Step 1).
/// Contains only planning fields — no PromptToSend (that's generated in Step 2).
/// </summary>
public class PlannerTaskItem
{
    public string Task { get; set; } = string.Empty;
    public string SkillName { get; set; } = string.Empty;
    public List<int> DependsOn { get; set; } = [];
}
