.create-or-alter function with (folder = "SRICM/Reconciliation", docstring = "Return latest snapshot data from cold path that is more recent than hot path", skipvalidation = "true") GetRatioReconciliationDataJson() {
    GetRatioReconciliationData() 
    | project 
        CaseNumber
        , IncidentId
        , IcMCloud
        , EventDateTime=Processtimestamp
        , Type="RATIO"
        , Content=bag_pack("Content", bag_pack("CaseNumber", CaseNumber, "Linkages", pack_array(bag_pack("Number", IncidentId, "Type", 'Automatic', "Source", 'RATIO', "DataBoundary", IcMCloud, "LinkedDateTime", Processtimestamp, "IncidentIdCloud", strcat(IncidentId, '-', IcMCloud), "Action", Action, "Reason", Reason))), "id", CaseNumber, "EventType", 'ratiolinkage', "RawProperties", bag_pack("UserProperties", bag_pack("EntityType", 'ratiolinkage', "EntityAction", Action, "EventDateTime", Processtimestamp, "EntityID", CaseNumber)), "createdBy", 'ReconciliationEngine', "modifiedBy", 'ReconciliationEngine',"SdpServiceName",'CXOAI', "createdOn", now(), "modifiedOn", now())
} 