.create-or-alter function with (folder = "SRICM/Reconciliation", docstring = "Return latest snapshot data from cold path that is more recent than hot path", skipvalidation = "true") GetSRSnapshotReconciliationData(windowoffsethours:int=-4) {
    let windowoffset = (windowoffsethours) * 1h;
    let windowlag = 10m;
    let beginwindowdate = now() + windowoffset; //Negative hours input, so add
    let endwindowdate = now() - windowlag;
    let currentutc = now();
    let cold = database("SupportValidationData").SupportCasesRawRecords 
    | extend SREventActionType=parse_json(Content).RawProperties.UserProperties.EventType 
    | where EntityType == 'Case' and SREventActionType <> 'Delete' 
    | project CaseNumber, EventDateTime, Content 
    | summarize arg_max(EventDateTime,*) by CaseNumber;
    let hot = database("ICMRatioData").SrSnapshot 
    | where SREventActionType <> 'Delete' 
    | extend ContentPacked=bag_pack("Content", Content, "RawProperties", RawProperties) 
    | project CaseNumber, EventDateTime, ContentPacked 
    | summarize arg_max(EventDateTime,*) by CaseNumber;
    cold
    | join kind=inner hot on $left.CaseNumber == $right.CaseNumber
    | where isempty(EventDateTime1) or (EventDateTime > EventDateTime1 and EventDateTime between (beginwindowdate .. endwindowdate))
} 