.create-or-alter function with (folder = "SRICM/Reconciliation", docstring = "Get Reconcilication data in tabular format", skipvalidation = "true") GetReconciliationData() {
    let newdata=ReconciliationData
    | extend x=strcat(CaseNumber,IncidentIds,IcMCloud,EventDateTime,Type)
    | project-away x;
    let history = ReconciliationDataHistory
    | summarize ReconciliationCount=count() by CaseNumber, IncidentIds, IcMCloud, EventDateTime, Type;
    newdata
    | join kind=leftouter  history on $left.CaseNumber == $right.CaseNumber and $left.IncidentIds == $right.IncidentIds and $left.EventDateTime == $right.EventDateTime and $left.Type == $right.Type
    | where ReconciliationCount <= 5
} 