.create-or-alter function with (folder = "SRICM", docstring = "Returns The SRs linked with the ICM for L1 aggregation", skipvalidation = "true") GetSRsByICMId_L1(IcmIds:dynamic, IcmDataboundary:string="PUBLIC") {
let databoundary=toupper(IcmDataboundary);
 //convert dynamics to table structure
let Icms= print Icm =IcmIds |mv-expand Icm|extend Icm=tostring(Icm);
//based on databoundry identify create possible IncidentIdCloud
let inputIcmWithBoundary=Icms| summarize Public=make_list(strcat(Icm,'-PUBLIC')),EU=make_list(strcat(Icm,'-EU'))| extend icms=iff(databoundary=='PUBLIC',Public,iff(databoundary =='EU',EU,array_concat(Public,EU))) | project-away Public,EU | mv-expand icms| extend icms=tostring(icms);
//get icms for which L1 aggrerate is returned
let directIcms= Icms| summarize icmspublic=make_list(strcat(Icm,'-PUBLIC')), icmseu=make_list(strcat(Icm,'-EU')) | extend icms=iff(databoundary=='PUBLIC',icmspublic,iff(databoundary =='EU',icmseu,array_concat(icmspublic,icmseu))) | project-away icmspublic,icmseu | mv-expand icms| extend icms=tostring(icms);
// get casenumbers for L1 aggregate ICMS
let CaseNumbers = toscalar(SrSnapshotByIcmNumberView | extend parts = split(SRNumIcmId, "-")| extend ICMId = parts[1]
    | where  strcat(ICMId,'-',DataBoundary) in (directIcms)
    | summarize max(EventDateTime) by CaseNumber | project CaseNumber| summarize casenumbers=make_list(CaseNumber)) ; 
//get L1 aggregate SR info for L1 aggregate Icms
let directsrs=SrSnapshotView
    | where CaseNumber in (CaseNumbers )
    |mv-expand LinkedICMs
    |extend IncidentIdCloud=tostring(LinkedICMs.IncidentIdCloud),
        Number=tostring(LinkedICMs.Number),
        IncidentDataBoundary=tostring(LinkedICMs.DataBoundary),
        Source=tostring(LinkedICMs.Source),
        Type=tostring(LinkedICMs.Type),
        LinkedDateTime=todatetime(LinkedICMs.LinkedDateTime)
    | where IncidentIdCloud in (directIcms)
    |project ICMId=Number, SupportRequestNumber=CaseNumber, SupportTopicTitle, Severity, CritSit, State, Status, Product=tostring(Product), SupportRegion, Customers=tostring(Customers), CreatedOn, IncidentId=Number,IncidentDataBoundary,  Source, LinkedDateTime, Type, ResourceId, AgentId, Age, ResolvedDateTime, AzureSubscriptionId, TenantId, ModifiedOn, DataBoundary,CaseUri,AggregationSource='Direct'
|order by ICMId,AggregationSource asc;
directsrs
}