.create-or-alter function with (folder = "ADF", docstring = "Return CaseNumber which needs to be expired in redis", skipvalidation = "true") GetRedisKeyToBeExpired() {
 let redis=ICMLinkageRedisKeyStore| summarize arg_max(TimeStamp,*) by CaseNumber;
redis| join kind=leftouter SrSnapshotView on CaseNumber
| extend idealttl=((now(7d) - now()) / 1m)
| where (State in ('Closed') or SREventActionType in ('Delete') or isempty(CaseNumber1)  ) and ttl > idealttl
| take 1000
| project CaseNumber,ttl,Prefix,State,SREventActionType,SdpModifiedOn
| extend packed = bag_pack(CaseNumber, 1)
| summarize Payload= make_bag(packed) by Prefix
| project Value=tostring(bag_pack("ActionType","SET","Payload",iif(isempty(Payload),dynamic({}),Payload)))
} 