.create-or-alter function with (folder = "SRICM", docstring = "Return Ratio ICMs which were overridden by DFM", skipvalidation = "true") GetRatioLinkageOverriddenIcms(fromdate:datetime) {
let allratiolinkage=RatioLinkage | summarize arg_max(EventDateTime,*) by CaseNumber | where EventDateTime > fromdate
|mv-expand Linkages
| extend Number=tostring(Linkages.Number)
| extend Type=tostring(Linkages.Type)
| extend Source=tostring(Linkages.Source)
| extend DataBoundary=tostring(Linkages.DataBoundary)
| extend IncidentIdCloud=tostring(Linkages.IncidentIdCloud)
| extend Action=tostring(Linkages.Action)
| extend LinkedDateTime=todatetime(Linkages.LinkedDateTime);
let valid= (allratiolinkage
|summarize Add=countif(Action=='Linked'),Removed=countif(Action!='Linked') by CaseNumber,Number,DataBoundary,IncidentIdCloud,Type,Source
| where Add >Removed) | join kind=inner allratiolinkage on CaseNumber,Number,DataBoundary,Type,Source
|project CaseNumber,Number,DataBoundary,IncidentIdCloud,Type,Source,LinkedDateTime;
valid | join kind=inner SrSnapshotView on CaseNumber
|mv-expand LinkedICMs
| extend ICMNumber=tostring(LinkedICMs.Number)
| extend ICMType=tostring(LinkedICMs.Type)
| extend ICMSource=tostring(LinkedICMs.Source)
| extend ICMDataBoundary=tostring(LinkedICMs.DataBoundary)
| extend ICMIncidentIdCloud=tostring(LinkedICMs.IncidentIdCloud)
| extend ICMLinkedDateTime=todatetime(LinkedICMs.LinkedDateTime)
| project CaseNumber,IncidentIdCloud,Number,Type,Source,DataBoundary,ICMNumber,ICMType,ICMSource,ICMDataBoundary,ICMIncidentIdCloud,ICMLinkedDateTime,LinkedDateTime
| where ICMIncidentIdCloud ==IncidentIdCloud and ICMSource !='RATIO'
| project CaseNumber, ICMNumber, ICMDataBoundary,ICMSource,ICMLinkedDateTime,RatioLinkedDateTime=LinkedDateTime,RatioSource=Source
|extend DurationOfVisibleRatioSourceInHours=datetime_diff('hour',ICMLinkedDateTime,RatioLinkedDateTime)
}