
.create-or-alter function with (folder = "ADF", docstring = "Get SrSnapshot Change Feed", skipvalidation = "true") GetSRSnapshotChangeFeed(startTime:datetime, endtime:datetime, batch:int, correctionReason:string, index:int) {
let skiprow=batch*index;
let dayStringMapping = 
    union 
    (print FieldPath = '$.SDPICMLinkageCorrection', Value = correctionReason, DataType='string' ),
    (print FieldPath = '$.SdpServiceName', Value = 'CXOAI',  DataType='string' );
let MetaData= toscalar(dayStringMapping |extend bag= bag_pack("FieldPath",FieldPath,"Value",Value,"DataType",DataType)| summarize make_list(bag) | project list_bag);
let latestSrs=ChangeFeedPipelineSRs|summarize arg_max(ExecutionTime,*) by CaseNumber|order by ModifiedOn asc| extend rownum=row_number()|where rownum >skiprow|take batch;
latestSrs| join kind=leftouter database('AceHubSupportData').CaseUriBackFill on CaseNumber | project-away CaseNumber1 //remove line
| join kind=inner SrSnapshotView on CaseNumber  |
where EventDateTime between (startTime.. endtime)  and isnotempty(State)
|order by ModifiedOn asc 
| extend Content=bag_merge(bag_remove_keys(Content,dynamic(["CaseUri"])),bag_pack("CaseUri",CaseUri)) //remove line
| extend Snapshot= bag_pack("Content",Content,"RawProperties",RawProperties)
| extend Value=bag_pack("Snapshot",Snapshot,"MetaData",MetaData,"Source","raw")
| project Key=CaseNumber,tostring(Value)
} 