.create-or-alter function with (folder = "SRICM", docstring = "Get Ratio Linkage Latency", skipvalidation = "true") GetRatioLinkageLatency(startTime:datetime, endtime:datetime) {
let ratiodata=RatioLinkage
| summarize arg_max(EventDateTime,*) by CaseNumber| where EventDateTime between (startTime .. endtime )
|mv-expand Linkages
|extend Number=tostring(Linkages.Number),Source=tostring(Linkages.Source), IncidentIdCloud=tostring(Linkages.IncidentIdCloud),LinkedDateTime=todatetime(Linkages.LinkedDateTime),Action=tostring(Linkages.Action),DataBoundary=tostring(Linkages.DataBoundary)
| project CaseNumber,Number,Source,IncidentIdCloud,LinkedDateTime,Action,DataBoundary;
let validdata=ratiodata|summarize Add=countif(Action=='Linked'),Removed=countif(Action != 'Linked') by CaseNumber,IncidentIdCloud,DataBoundary,Number,Source
|where Add>Removed
|join kind=inner ratiodata on CaseNumber,IncidentIdCloud
|project CaseNumber,Number,Source,IncidentIdCloud,LinkedDateTime,Action,DataBoundary;
let srjoin=validdata|join kind=inner SrSnapshot on CaseNumber
|project CaseNumber,Number,Source,IncidentIdCloud,LinkedDateTime,Action,DataBoundary,CreatedOn,ModifiedOn,EventDateTime
|where isnotempty(CreatedOn ) and isnotempty( ModifiedOn)
|where EventDateTime < LinkedDateTime
|summarize arg_max(EventDateTime,*)by CaseNumber
|extend LatencyRatioLinkages=datetime_diff('minute',LinkedDateTime,EventDateTime)
|where EventDateTime > todatetime('2025-06-01') | order by EventDateTime;
srjoin
}