.create-or-alter function with (folder = "ADF", docstring = "Get RatioLinkage Change Feed Count", skipvalidation = "true") GetRatioLinkageChangeFeedCount(startTime:datetime, endtime:datetime, batch:int, index:int) {
let skiprow=batch*index;
let latestIncidentLinkages=ChangeFeedPipelineRatioLinkage|summarize arg_max(ExecutionTime,*) by CaseNumber;
latestIncidentLinkages|order by EventDateTime asc| extend rownum=row_number()|where rownum >skiprow|take batch| count
}