.create-or-alter function with (folder = "ADF", docstring = "Get Missing Ratio Linkage ", skipvalidation = "true") GetIncidentLinkageMissingEvent(executionTime:datetime) {
IncidentLinkageView 
| where LinkSource=="RATIO"
|mv-expand Aggregate_Add
| extend IncidentIdCloud=tostring(Aggregate_Add.IncidentIdCloud) 
| extend Number=split(IncidentIdCloud, "-")[0] 
|extend isint=toint(Number) 
| where isempty(isint) 
|distinct CaseNumber,EventDateTime 
| where EventDateTime between (todatetime("2001-01-01").. todatetime(executionTime)) 
|order by EventDateTime asc 
| project CaseNumber,EventDateTime,executionTime
} 
