.create-or-alter function with (folder = "ADF", docstring = "Get SrChange Change Feed", skipvalidation = "true") GetSRChangeChangeFeed(startTime:datetime, endtime:datetime, batch:int, correctionReason:string, index:int) {
// let startTime=datetime('2001-01-01');
// let endtime=now();
// let batch=50000;
// let correctionReason='';
// let index=0;
//
let currentTime=now();
let skiprow=batch*index;
let latestSrs=ChangeFeedPipelineSRChange|summarize arg_max(ExecutionTime,*) by CaseNumber|order by ModifiedOn asc| extend rownum=row_number()|where rownum >skiprow|take batch;
let srinfo=materialize(SrSnapshotView| where CaseNumber in (latestSrs| distinct  CaseNumber) and EventDateTime between (startTime.. endtime) |order by ModifiedOn asc 
| mv-expand  Customers
| extend Customer=bag_pack('CustomerName',tostring(Customers.CustomerName),'CustomerType',tostring(Customers.CustomerType))
| summarize Customers = make_list(Customer) by CaseNumber,SREventActionType,CritSit,State,Severity,Status,tostring(Product),DataBoundary,tostring(LinkedICMs),ModifiedOn,CreatedOn,ModifiedBy,CreatedBy,AzureSubscriptionId,SupportTopicTitle,SupportRegion,ResourceId,AgentId,Age,ResolvedDateTime,TenantId,CaseUri
|extend LinkedICMs=todynamic(LinkedICMs),Product=todynamic(Product)
| extend Snapshot=bag_pack('CaseNumber',CaseNumber,'SREventActionType',SREventActionType,'CritSit',CritSit,'State',State,'Severity',Severity,'Status',Status,
'Product',Product,'DataBoundary',DataBoundary,'LinkedICMs',LinkedICMs,'ModifiedOn',ModifiedOn,'CreatedOn',CreatedOn,'ModifiedBy',ModifiedBy,'CreatedBy',CreatedBy,'AzureSubscriptionId',AzureSubscriptionId,
'Customers',Customers,'SupportTopicTitle',SupportTopicTitle,'SupportRegion',SupportRegion,'ResourceId',ResourceId,'AgentId',AgentId,'Age',Age,'ResolvedDateTime',ResolvedDateTime,'TenantId',TenantId,
'CaseUri',CaseUri)
|mv-expand LinkedICMs
|extend SrNumber=tostring(LinkedICMs.Number),SrType=tostring(LinkedICMs.Type),SrSource=tostring(LinkedICMs.Source),SrDataBoundary=tostring(LinkedICMs.DataBoundary),SrIncidentIdCloud=tostring(LinkedICMs.IncidentIdCloud),SrLinkedDateTime=tostring(LinkedICMs.LinkedDateTime)
|project CaseNumber,SrNumber,SrType,SrSource,SrDataBoundary,SrIncidentIdCloud,SrLinkedDateTime,Snapshot=tostring(Snapshot)
| extend pk= bag_pack('Number',SrNumber,'Type',SrType,'Source',SrSource,'DataBoundary',SrDataBoundary,'IncidentIdCloud',SrIncidentIdCloud,'LinkedDateTime',SrLinkedDateTime)
| extend withaction= bag_pack('Number',SrNumber,'Type',SrType,'Source',SrSource,'DataBoundary',SrDataBoundary,'IncidentIdCloud',SrIncidentIdCloud,'LinkedDateTime',SrLinkedDateTime,'Action','Linked')
| summarize ICMLinkChange= make_set(withaction),CurrentValue=make_set(pk),PreviousValue=todynamic('[]') by CaseNumber,Snapshot
|extend Changes=bag_pack('LinkedICMs',bag_pack('PreviousValue',PreviousValue,'CurrentValue',CurrentValue,'ICMLinkChange',ICMLinkChange),'SDPICMLinkageCorrection',bag_pack('PreviousValue','','CurrentValue',correctionReason))
| extend ChangeProperties=todynamic('["LinkedICMs","SDPICMLinkageCorrection"]'),Snapshot=todynamic(Snapshot),EventDateTime=currentTime,SupportRequestNumber=CaseNumber,EventType='propertychange',SdpInternal=bag_pack('IngestorRecievedTime',currentTime,'CornerStoneServiceBusEnqueueTime',currentTime,'CornerStoneEventhubEnqueueTime',currentTime)
|extend ChangeEvent=bag_pack('SupportRequestNumber',SupportRequestNumber,'EventDateTime',EventDateTime,'EventType',EventType,'ChangeProperties',ChangeProperties,'Changes',Changes,'Snapshot',Snapshot,'SdpInternal',SdpInternal)
| project-away PreviousValue,CurrentValue,ICMLinkChange,Snapshot,Changes,ChangeProperties,EventDateTime,SupportRequestNumber,EventType,SdpInternal
);
srinfo| project Key=CaseNumber,Value=tostring(ChangeEvent)
}