.create-or-alter function with (folder = "ADF", docstring = "Get SrSnapshot Purged Linkage Correction Event", skipvalidation = "true") GetSrSnapshotPurgedLinkageCorrectionEvent(executionTime:datetime) {
let maxSnapshotId=toscalar(database('SAData').external_table("msdfm_deletedcasehistory_Public")| summarize max(snapshotid));
let purgeCases=database('SAData').external_table("msdfm_deletedcasehistory_Public")| where snapshotid == maxSnapshotId and strlen( msdfm_ticketnumber)==16 | extend prefix= toint(substring(msdfm_ticketnumber,0,2)) | where prefix >10
| extend PurgedOn=todatetime(modifiedon),CaseNumber=msdfm_ticketnumber
| where PurgedOn > datetime('2025-08-09 00:00:00.0000000')| project CaseNumber,PurgedOn
|join kind=inner SrSnapshotView on CaseNumber | where SREventActionType !='DeleteUpdated'| order by CaseNumber asc | project CaseNumber,PurgedOn;
SrSnapshotView|join kind=inner purgeCases on CaseNumber
| order by EventDateTime 
| project CaseNumber,ModifiedOn=PurgedOn,executionTime
| order by ModifiedOn asc
}