.create-or-alter  materialized-view  with ( folder='SRICM',docString='SrSnapshot pivoted by ICM Id',autoUpdateSchema=true) SrSnapshotByIcmNumberView on table SrSnapshot { SrSnapshot
    | mv-expand LinkedICMs
    | extend
        SupportRequestNumber = CaseNumber,
        ICMId               = toint(LinkedICMs.Number),
        Type                = tostring(LinkedICMs.Type),
        Source              = tostring(LinkedICMs.Source),
        DataBoundary        = tostring(LinkedICMs.DataBoundary),
        LinkedDateTime      = todatetime(LinkedICMs.LinkedDateTime),
        SRNumIcmId          = strcat(CaseNumber, '-', LinkedICMs.Number, '-', LinkedICMs.DataBoundary)
    | summarize arg_max(EventDateTime, *) 
        by SRNumIcmId } 