<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CXOAI.Tools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.8.0-beta.1" />
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.7.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
	<PackageReference Include="System.IO.Packaging" Version="10.0.5" />
    <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc3" />
    <PackageReference Include="Microsoft.Azure.Kusto.Data" Version="14.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.46.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Services\AppServices\CXOAI.AppServices\AppServices.csproj" />
    <ProjectReference Include="..\..\Common\Services\ConfigurationStoreService\ConfigurationStoreService.csproj" />
    <ProjectReference Include="..\..\Common\Services\SkillFramework\SkillFramework.csproj" />
    <ProjectReference Include="..\..\Common\Services\StatusNotifierService\StatusNotifierService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Configuration\KnowledgeGraph.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Configuration\NLTKqlSchemaGraph.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestData\" />
  </ItemGroup>

</Project>
