@echo off
setlocal
REM Define variables
set SERVICE_GROUP_FORMAT=Microsoft.Azure.EngOps.CXOAI.{0}-sg
set ENVIROMENTS=Test,Ppe,Prvw,Prod
set BICEPDIRECTORY=D:\src\EngOps-CXObserve-AI\CXOAI\DotNet\DeploymentArtifacts\CXOAI\Biceps
set SERVICETREEID=61b4b63c-3588-445e-a558-5352b1bd06c2
set APP_NAME=cxoai
set GENERATE_EV2_FOR_ORCHESTRATOR=func
set SERVICEGROUP_DEFINATION_NAME_FORMAT=engOps-eng-CXOAI-public-{0}-ev2-srg
set SUBSCRIPTION_KEY_FORMAT=CXOAI{0}SubscriptionKey
set TEAMEMAIL=madhulikafte@microsoft.com
set MOVETOAPPDIRECTORY=true
set TESTOWNERGROUPOBJECTID=da3e29ee-69a0-4d37-8405-a90c33c4e392
set PRODOWNERGROUPOBJECTID=60012848-5ae7-4d4d-931a-191222984335
BicepToEv2 --sgf %SERVICE_GROUP_FORMAT% --envs %ENVIROMENTS% --d %BICEPDIRECTORY% --stid %SERVICETREEID% --appname %APP_NAME% --rgdnf %SERVICEGROUP_DEFINATION_NAME_FORMAT% ^
 --skeyf %SUBSCRIPTION_KEY_FORMAT% --email %TEAMEMAIL% --togid %TESTOWNERGROUPOBJECTID% --pogid %PRODOWNERGROUPOBJECTID% --gev2o %GENERATE_EV2_FOR_ORCHESTRATOR% --move2appdir %MOVETOAPPDIRECTORY%
pause
endlocal
